model_name_or_path: 'google/flan-t5-base'
train_batch_size: 12
eval_batch_size: 11
logger: wandb
warmup_steps: 2000
learning_rate: 5e-5
num_train_epochs: 10
gradient_accumulation_steps: 5
num_workers: 8
adam_epsilon: 1e-6
data_path: 'data/processed'
wb_name: "wikihow-test"
wb_project: "FLAN-summarizer"
wb_entity: "jordanclive"
val_check_interval: 1
max_seq_length: 100
#label_smoothing: 0.2

num_sanity_val_steps: -1
test_outputs: outputs
gpus: 2
visible_devices: "1,2"
val_metric: 'rouge2'
#offline: True
#local: True
#debug_mode: True
# load_checkpoint: True
#skip_val: False
